=begin
 第三方类库
=end
#source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

link_with 'JuYou', 'JuYou Tests'

pod 'MJRefresh'
pod 'MJExtension'
pod 'JGProgressHUD'
pod 'SDWebImage'
#网络请求库
pod 'Alamofire'

pod 'FDFullscreenPopGesture'
